site_name: molforge
site_description: A unified Python library for structural bioinformatics, MD, and ML.
repo_url: https://github.com/DoctorDean/molforge
repo_name: DoctorDean/molforge

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - Architecture: ../architecture/overview.md

docs_dir: docs/source

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [src]

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
