"""Tests for the fpocket pocket-detection wrapper.

The fpocket binary is rarely available in CI (no pip package; users
install via system package manager or build from source), so the
strategy mirrors test_vina.py / test_rosettafold.py: end-to-end
tests skip when the binary is missing, and the parser is tested in
isolation against synthetic fpocket output. The parser is the
non-trivial logic; the subprocess invocation is a thin shell.
"""

from __future__ import annotations

import shutil
import textwrap
from pathlib import Path

import numpy as np
import pytest

from molforge.core import AtomArray, Protein
from molforge.core import metadata_keys as mk
from molforge.core.provenance import Provenance
from molforge.docking import Pocket
from molforge.wrappers.pockets import FpocketNotInstalledError, detect_pockets
from molforge.wrappers.pockets.fpocket import (
    _maybe_float,
    _parse_fpocket_output,
    _parse_info_txt,
)

# ---------------------------------------------------------------------
# Synthetic fixtures
# ---------------------------------------------------------------------


_REAL_FPOCKET_INFO_BLOCK = textwrap.dedent(
    """\
    Pocket 1 :
    \tScore : \t\t\t0.490
    \tDruggability Score : \t0.019
    \tNumber of Alpha Spheres : \t21
    \tTotal SASA : \t\t19.687
    \tPolar SASA : \t\t7.611
    \tApolar SASA : \t\t12.076
    \tVolume : \t\t270.934
    \tMean local hydrophobic density : \t3.000
    \tMean alpha sphere radius : \t3.816
    \tMean alp. sph. solvent access : \t0.519
    \tApolar alpha sphere proportion : \t0.190
    \tHydrophobicity score : \t23.889

    Pocket 2 :
    \tScore : \t\t\t0.320
    \tDruggability Score : \t0.005
    \tNumber of Alpha Spheres : \t14
    \tVolume : \t\t150.000

    Pocket 3 :
    \tScore : \t\t\t0.180
    \tDruggability Score : \t0.001
    \tNumber of Alpha Spheres : \t8
    \tVolume : \t\t80.000
    """
)


_REAL_VERT_PQR = textwrap.dedent(
    """\
    REMARK   1 PQR file generated by fpocket
    ATOM      1  C   STP A   1      10.000  20.000  30.000  0.00  2.00
    ATOM      2  C   STP A   1      11.000  21.000  31.000  0.00  2.00
    ATOM      3  C   STP A   1      12.000  22.000  32.000  0.00  2.00
    END
    """
)


_REAL_POCKET_ATM_PDB = textwrap.dedent(
    """\
    ATOM      1  N   ALA A  17       0.000   0.000   0.000  1.00 20.00           N
    ATOM      2  CA  ALA A  17       1.458   0.000   0.000  1.00 20.00           C
    ATOM      3  C   ALA A  17       2.000   1.420   0.000  1.00 20.00           C
    ATOM      4  N   GLY A  18       3.314   1.420   0.000  1.00 20.00           N
    ATOM      5  CA  GLY A  18       4.000   2.840   0.000  1.00 20.00           C
    END
    """
)


def _minimal_protein() -> Protein:
    """A tiny Protein that satisfies the type but doesn't need to
    pass through fpocket. Used for testing the error paths where
    the actual coordinates don't matter."""
    return Protein(AtomArray(0))


# ---------------------------------------------------------------------
# Parser tests (no binary needed)
# ---------------------------------------------------------------------


class TestInfoTxtParser:
    """The headline parser: turn fpocket's info.txt into per-pocket
    descriptor dicts. These tests use real-shape fpocket output (the
    exact format documented in fpocket's GETTINGSTARTED.md)."""

    def test_parses_three_pockets(self) -> None:
        result = _parse_info_txt(_REAL_FPOCKET_INFO_BLOCK)
        assert len(result) == 3

    def test_extracts_headline_descriptors(self) -> None:
        result = _parse_info_txt(_REAL_FPOCKET_INFO_BLOCK)
        first = result[0]
        # The three molforge cares most about.
        assert first["Score"] == "0.490"
        assert first["Druggability Score"] == "0.019"
        assert first["Volume"] == "270.934"
        # A few of the extras that go into metadata["descriptors"].
        assert first["Number of Alpha Spheres"] == "21"
        assert first["Polar SASA"] == "7.611"

    def test_handles_pockets_with_fewer_descriptors(self) -> None:
        # Pocket 3 in the fixture has only 4 descriptors; the parser
        # shouldn't require any particular set to be present.
        result = _parse_info_txt(_REAL_FPOCKET_INFO_BLOCK)
        third = result[2]
        assert "Score" in third
        assert "Volume" in third
        assert "Polar SASA" not in third  # absent in this block

    def test_empty_input_returns_empty_list(self) -> None:
        assert _parse_info_txt("") == []
        assert _parse_info_txt("   \n\n   \n") == []

    def test_handles_pockets_without_blank_lines(self) -> None:
        """fpocket's actual output sometimes runs blocks together
        without blank lines. The parser shouldn't depend on them."""
        compact = (
            "Pocket 1 :\n\tScore : 0.5\n\tVolume : 100\nPocket 2 :\n\tScore : 0.3\n\tVolume : 50\n"
        )
        result = _parse_info_txt(compact)
        assert len(result) == 2
        assert result[0]["Score"] == "0.5"
        assert result[1]["Volume"] == "50"

    def test_ignores_lines_outside_a_pocket_block(self) -> None:
        """Leading or trailing junk that fpocket might emit (banners,
        version info, etc.) shouldn't yield phantom pockets."""
        text = "fpocket version 4.0\nSome banner text\nPocket 1 :\n\tScore : 0.5\n\tVolume : 100\n"
        result = _parse_info_txt(text)
        assert len(result) == 1


class TestMaybeFloat:
    def test_valid_float(self) -> None:
        assert _maybe_float("3.14") == 3.14

    def test_integer_string(self) -> None:
        assert _maybe_float("21") == 21.0

    def test_none_input(self) -> None:
        assert _maybe_float(None) is None

    def test_non_numeric_returns_none(self) -> None:
        # Whatever fpocket might emit for a missing/unknown value.
        assert _maybe_float("N/A") is None
        assert _maybe_float("") is None
        assert _maybe_float("inf garbage") is None

    def test_actual_inf(self) -> None:
        # Python's float() accepts "inf" — that's not a bug;
        # documenting the behaviour here.
        assert _maybe_float("inf") == float("inf")


# ---------------------------------------------------------------------
# End-to-end parser test (no binary, synthesized output dir)
# ---------------------------------------------------------------------


class TestParseFpocketOutput:
    """Build a synthetic fpocket output directory and parse it.
    Exercises the full _parse_fpocket_output path including the
    vert.pqr / atm.pdb side-files and Provenance attachment."""

    @pytest.fixture
    def synthetic_out_dir(self, tmp_path: Path) -> Path:
        out_dir = tmp_path / "structure_out"
        (out_dir / "pockets").mkdir(parents=True)
        (out_dir / "structure_info.txt").write_text(_REAL_FPOCKET_INFO_BLOCK)
        # Only provide vert.pqr and atm.pdb for the first pocket;
        # the parser should still produce 3 pockets, with the
        # missing-file ones having NaN center and empty residues.
        (out_dir / "pockets" / "pocket0_vert.pqr").write_text(_REAL_VERT_PQR)
        (out_dir / "pockets" / "pocket0_atm.pdb").write_text(_REAL_POCKET_ATM_PDB)
        return out_dir

    def test_returns_three_pockets(self, synthetic_out_dir: Path) -> None:
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        assert len(pockets) == 3

    def test_first_pocket_has_center_from_vert_pqr(self, synthetic_out_dir: Path) -> None:
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        # vert.pqr has alpha spheres at (10,20,30), (11,21,31),
        # (12,22,32); the centre is the mean.
        np.testing.assert_array_almost_equal(
            pockets[0].center, np.array([11.0, 21.0, 31.0], dtype=np.float32)
        )

    def test_first_pocket_has_lining_residues(self, synthetic_out_dir: Path) -> None:
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        # The atm.pdb fixture has ALA 17 and GLY 18, both chain A.
        assert pockets[0].residues == [("A", 17, ""), ("A", 18, "")]

    def test_descriptor_extraction(self, synthetic_out_dir: Path) -> None:
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        # Pocket 1's headline descriptors from the fixture.
        assert pockets[0].score == 0.490
        assert pockets[0].druggability == 0.019
        assert pockets[0].volume == 270.934
        # rank is 0-indexed; pocket 1 in info.txt -> rank 0.
        assert pockets[0].rank == 0
        # The full descriptor dict is preserved in metadata.
        assert pockets[0].metadata["descriptors"]["Polar SASA"] == "7.611"

    def test_missing_side_files_yield_nan_center(self, synthetic_out_dir: Path) -> None:
        """Pockets 1 and 2 have no vert.pqr / atm.pdb in this fixture
        (only pocket0_*.* was created). They should still appear in
        the output with NaN centre and empty residue list — the
        descriptors from info.txt are the source of truth and shouldn't
        be discarded just because a side-file is absent."""
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        assert np.isnan(pockets[1].center).all()
        assert pockets[1].residues == []
        # The headline descriptors still came through.
        assert pockets[1].score == 0.320
        assert pockets[1].volume == 150.000

    def test_provenance_attached_and_shared(self, synthetic_out_dir: Path) -> None:
        """All pockets from one call share the same Provenance
        object — same pattern as ProteinMPNN's DesignedSequence
        (frozen + immutable, by-reference sharing is safe)."""
        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=_minimal_protein(),
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        provs = [p.metadata[mk.PROVENANCE] for p in pockets]
        # All three reference the SAME Provenance object.
        assert provs[0] is provs[1] is provs[2]
        # Right engine name + parameters + inputs.
        assert provs[0].engine == "fpocket"
        assert "fpocket_executable" in provs[0].parameters
        assert "min_alpha_spheres" in provs[0].parameters
        assert "protein" in provs[0].inputs

    def test_provenance_chains_to_input_protein(self, synthetic_out_dir: Path) -> None:
        """When the input Protein has its own Provenance (e.g. from
        ESMFold), fpocket's chains back through it — the headline
        cross-engine scenario."""
        protein = _minimal_protein()
        protein.metadata[mk.PROVENANCE] = Provenance.from_engine(
            engine="ESMFold",
            parameters={"model_name": "esmfold_v1"},
            inputs={"sequence": "AAA"},
        )

        pockets = _parse_fpocket_output(
            synthetic_out_dir,
            protein=protein,
            fpocket_executable="fpocket",
            min_alpha_spheres=None,
            min_volume=None,
        )
        chain = pockets[0].metadata[mk.PROVENANCE].chain()
        engines = [step.engine for step in chain]
        assert engines == ["ESMFold", "fpocket"]


# ---------------------------------------------------------------------
# Top-level error paths (no binary needed)
# ---------------------------------------------------------------------


class TestDetectPocketsErrors:
    def test_missing_binary_raises_friendly_error(self) -> None:
        protein = _minimal_protein()
        with pytest.raises(FpocketNotInstalledError) as exc:
            detect_pockets(protein, fpocket_executable="/nonexistent/fpocket")
        # The error message points at install guidance.
        msg = str(exc.value)
        assert "fpocket binary not found" in msg
        # Mentions at least one install path so users don't have to
        # grep docs.
        assert any(s in msg for s in ("brew", "apt", "github"))


# ---------------------------------------------------------------------
# End-to-end (real fpocket binary)
# ---------------------------------------------------------------------


@pytest.mark.skipif(shutil.which("fpocket") is None, reason="fpocket binary not installed")
class TestRealFpocket:
    """Run the real fpocket binary against a small real structure.
    Skipped in CI by default since fpocket isn't pip-installable.
    Run locally with fpocket on $PATH to exercise the full pipeline."""

    def test_detects_at_least_one_pocket_on_ubiquitin(self, tmp_path: Path) -> None:
        from molforge.io import fetch

        protein = fetch("1UBQ")
        pockets = detect_pockets(protein)
        # 1UBQ is a small protein but fpocket should find a few
        # pockets (the canonical Ile44 patch and a couple more).
        assert len(pockets) >= 1

        top = pockets[0]
        assert isinstance(top, Pocket)
        assert top.center.shape == (3,)
        assert not np.isnan(top.center).any()
        assert top.score is not None
        # Provenance attached.
        assert mk.PROVENANCE in top.metadata
