"""Tests for the PQR (PDB2PQR / APBS) reader and writer.

PQR is a PDB-like format that appends per-atom partial charge and
atomic radius as whitespace-separated trailing fields. The reader
parses columns 1-54 as fixed-position (PDB-compatible coordinates)
and whitespace-splits the rest for charge and radius — handling the
varying-width tail that different generators emit.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from molforge.core import Protein
from molforge.io.pqr import (
    _DEFAULT_RADIUS,
    _parse_charge_radius,
    read_pqr,
    read_pqr_string,
    write_pqr,
)

# Realistic PDB2PQR output for a 5-atom alanine.
_SAMPLE_PQR = """REMARK   1 PQR file generated by PDB2PQR
ATOM      1  N   ALA A   1      27.340  24.430   2.614 -0.3090  1.8240
ATOM      2  CA  ALA A   1      26.266  25.413   2.842  0.1414  1.9080
ATOM      3  C   ALA A   1      26.913  26.639   3.531  0.5973  1.9080
ATOM      4  O   ALA A   1      27.886  26.463   4.263 -0.5679  1.6612
ATOM      5  CB  ALA A   1      25.112  24.880   3.649 -0.1825  1.9080
END
"""


# ---------------------------------------------------------------------
# Charge/radius extractor
# ---------------------------------------------------------------------


class TestChargeRadiusExtractor:
    def test_two_clean_floats(self) -> None:
        c, r = _parse_charge_radius("  -0.3090  1.8240")
        assert c == pytest.approx(-0.309)
        assert r == pytest.approx(1.824)

    def test_extra_trailing_tokens_ignored(self) -> None:
        """Some PQR writers append an atom-type description after the
        radius. The non-numeric trailer is ignored and charge/radius
        are still picked up."""
        c, r = _parse_charge_radius("  -0.5  1.8  extra-description")
        assert c == pytest.approx(-0.5)
        assert r == pytest.approx(1.8)

    def test_occupancy_bfactor_prefix_taken_as_last_two(self) -> None:
        """When a PQR line retains the PDB occupancy (1.00) and B-factor
        (0.00) columns before the appended charge and radius, the *last*
        two floats are charge and radius — taking the first two would
        misread the occupancy/B-factor pair."""
        c, r = _parse_charge_radius("  1.00  0.00 -0.3090  1.8240")
        assert c == pytest.approx(-0.309)
        assert r == pytest.approx(1.824)

    def test_empty_tail_returns_defaults(self) -> None:
        c, r = _parse_charge_radius("")
        assert c == pytest.approx(0.0)
        assert r == pytest.approx(_DEFAULT_RADIUS)

    def test_only_one_float_returns_defaults(self) -> None:
        """A tail with only a single parseable float is treated as
        missing data — we'd rather return defaults than guess which
        field was intended."""
        c, r = _parse_charge_radius("  -0.5")
        assert c == pytest.approx(0.0)
        assert r == pytest.approx(_DEFAULT_RADIUS)


# ---------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------


class TestReadPqrString:
    def test_returns_protein(self) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        assert isinstance(prot, Protein)
        assert prot.atom_array.n_atoms == 5

    def test_coordinates_parsed(self) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        assert tuple(prot.atom_array.coords[0]) == pytest.approx((27.340, 24.430, 2.614), abs=1e-3)

    def test_charges_populated(self) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        np.testing.assert_allclose(
            prot.atom_array.charge,
            [-0.309, 0.1414, 0.5973, -0.5679, -0.1825],
            atol=1e-3,
        )

    def test_radii_attached_to_metadata(self) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        radii = prot.metadata.get("radii")
        assert radii is not None
        np.testing.assert_allclose(radii, [1.824, 1.908, 1.908, 1.6612, 1.908], atol=1e-3)

    def test_empty_input_yields_empty_protein(self) -> None:
        prot = read_pqr_string("")
        assert prot.atom_array.n_atoms == 0


# ---------------------------------------------------------------------
# Variant-width tails
# ---------------------------------------------------------------------


class TestVariantTails:
    def test_amber_style_wider_charges(self) -> None:
        """Some emitters pad the charge column wider than PDB2PQR's
        default — the whitespace-split parser handles it."""
        text = "ATOM      1  N   ALA A   1      27.340  24.430   2.614    -0.30900    1.82400\n"
        prot = read_pqr_string(text)
        assert prot.atom_array.n_atoms == 1
        assert prot.atom_array.charge[0] == pytest.approx(-0.309, abs=1e-3)
        assert prot.metadata["radii"][0] == pytest.approx(1.824, abs=1e-3)

    def test_extra_trailing_string_tolerated(self) -> None:
        """A trailing atom-type description (some PDB2PQR variants
        emit this) doesn't disturb charge/radius extraction."""
        text = "ATOM      1  N   ALA A   1      27.340  24.430   2.614 -0.3090  1.8240 N3\n"
        prot = read_pqr_string(text)
        assert prot.atom_array.charge[0] == pytest.approx(-0.309, abs=1e-3)
        assert prot.metadata["radii"][0] == pytest.approx(1.824, abs=1e-3)

    def test_retained_occupancy_bfactor_columns(self) -> None:
        """A PQR record that kept the leftover PDB occupancy (1.00) and
        B-factor (0.00) columns before charge/radius must still read the
        true charge and radius, not the occupancy/B-factor pair."""
        text = "ATOM      1  N   ALA A   1      27.340  24.430   2.614  1.00  0.00 -0.3090  1.8240\n"
        prot = read_pqr_string(text)
        assert prot.atom_array.charge[0] == pytest.approx(-0.309, abs=1e-3)
        assert prot.metadata["radii"][0] == pytest.approx(1.824, abs=1e-3)


# ---------------------------------------------------------------------
# File reading + dispatcher
# ---------------------------------------------------------------------


class TestReadFromDisk:
    def test_read_file(self, tmp_path: Path) -> None:
        fp = tmp_path / "x.pqr"
        fp.write_text(_SAMPLE_PQR)
        prot = read_pqr(fp)
        assert prot.atom_array.n_atoms == 5

    def test_dispatcher_load_routes_to_pqr(self, tmp_path: Path) -> None:
        from molforge.io import load

        fp = tmp_path / "x.pqr"
        fp.write_text(_SAMPLE_PQR)
        prot = load(fp)
        assert isinstance(prot, Protein)
        assert prot.atom_array.n_atoms == 5

    def test_dispatcher_save_routes_to_pqr(self, tmp_path: Path) -> None:
        from molforge.io import load, save

        fp_in = tmp_path / "in.pqr"
        fp_in.write_text(_SAMPLE_PQR)
        prot = read_pqr(fp_in)
        fp_out = tmp_path / "out.pqr"
        save(prot, fp_out)
        assert fp_out.is_file()
        rt = load(fp_out)
        assert rt.atom_array.n_atoms == prot.atom_array.n_atoms


# ---------------------------------------------------------------------
# Writing and round-trip
# ---------------------------------------------------------------------


class TestWriteRoundTrip:
    def test_round_trip_preserves_atom_count(self, tmp_path: Path) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        fp = tmp_path / "out.pqr"
        write_pqr(prot, fp)
        rt = read_pqr(fp)
        assert rt.atom_array.n_atoms == prot.atom_array.n_atoms

    def test_round_trip_preserves_coordinates(self, tmp_path: Path) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        fp = tmp_path / "out.pqr"
        write_pqr(prot, fp)
        rt = read_pqr(fp)
        np.testing.assert_allclose(rt.atom_array.coords, prot.atom_array.coords, atol=1e-3)

    def test_round_trip_preserves_charges(self, tmp_path: Path) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        fp = tmp_path / "out.pqr"
        write_pqr(prot, fp)
        rt = read_pqr(fp)
        np.testing.assert_allclose(rt.atom_array.charge, prot.atom_array.charge, atol=1e-3)

    def test_round_trip_preserves_radii(self, tmp_path: Path) -> None:
        prot = read_pqr_string(_SAMPLE_PQR)
        fp = tmp_path / "out.pqr"
        write_pqr(prot, fp)
        rt = read_pqr(fp)
        np.testing.assert_allclose(rt.metadata["radii"], prot.metadata["radii"], atol=1e-3)

    def test_write_falls_back_to_default_radius(self, tmp_path: Path) -> None:
        """A Protein without metadata['radii'] still writes a valid
        PQR, using the default 1.5 Å radius for every atom."""
        prot = read_pqr_string(_SAMPLE_PQR)
        # Drop the radii so the writer must fall back.
        prot.metadata = {k: v for k, v in prot.metadata.items() if k != "radii"}
        fp = tmp_path / "out.pqr"
        write_pqr(prot, fp)
        rt = read_pqr(fp)
        for r in rt.metadata["radii"]:
            assert r == pytest.approx(_DEFAULT_RADIUS, abs=1e-3)
